(define-module (odoo odoo)
  #:use-module ((guix licenses)
                #:select (lgpl3))
  #:use-module ((guix licenses) #:select (lgpl3) #:prefix license:)

  #:use-module (gnu packages)
  #:use-module (gnu packages check)
  #:use-module (gnu packages pdf)
  #:use-module (gnu packages databases)
  #:use-module (gnu packages python-web)
  #:use-module (gnu packages libusb)
  #:use-module (gnu packages finance)
  #:use-module (gnu packages openldap)
  #:use-module (gnu packages time)
  #:use-module (gnu packages graphviz)
  #:use-module (gnu packages python-crypto)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-build)
  #:use-module (gnu packages python-xyz)
  #:use-module (guix packages)
  #:use-module (guix search-paths)
  #:use-module (guix download)
  #:use-module (guix utils)
  #:use-module (guix build-system python)
)
(define-public odoo
  (package
    (name "odoo")
    (version "15")
    (source
     (origin
       (method url-fetch)
       (uri (string-append
"https://nightly.odoo.com/15.0/nightly/tgz/odoo_15.0.latest.tar.gz"
)) (sha256
        (base32
         "0yrm86h0njbdikfc7385zxm89vbvqcfzv5mz7mihixqxbdkvlicl"))))
    (build-system python-build-system)
    (native-inputs
     `(("python-setuptools" ,python-setuptools)
       ("python", python-wrapper)
       ;("xlwt", python-xlwt)
       ("xlsxwriter", python-xlsxwriter)
("email-validator", python-email-validator)
("mock", python-mock)
("Babel", python-babel)
("chardet", python-chardet)
("decorator", python-decorator)
("docutils", python-docutils)
;("ebaysdk", python-ebaysdk)
("freezegun", python-freezegun)
("freezegun", python-freezegun)
("gevent", python-gevent)
("greenlet", python-greenlet)
("idna", python-idna)
("Jinja2", python-jinja2)
("libsass", python-libsass)
("lxml", python-lxml)
("MarkupSafe", python-markupsafe)
;("num2words", python-num2words)
("ofxparse", python-ofxparse)
("passlib", python-passlib)
("Pillow", python-pillow)
("polib", python-polib)
("psutil", python-psutil)
("psycopg2", python-psycopg2)
("pydot", python-pydot)
("pyopenssl", python-pyopenssl)
("PyPDF2", python-pypdf2)
;("pypiwin32", python-pypiwin32)
("pyserial", python-pyserial)
("python-dateutil", python-dateutil)
("python-ldap", python-ldap)
("python-stdnum", python-stdnum)
("pytz", python-pytz)
("pyusb", python-pyusb)
("qrcode", python-qrcode)
("reportlab", python-reportlab)
("requests", python-requests)
("urllib3", python-urllib3)
("vobject", python-vobject)
("Werkzeug", python-werkzeug)
("xlrd", python-xlrd)
("XlsxWriter", python-xlsxwriter)
("xlwt", python-xlwt)
("zeep", python-zeep)

       ))

    (arguments
     `(#:python ,python-3
       #:tests? #f))

    (home-page "http://www.odoo.com")
    (synopsis
     "ERP")
    (description
     "ERP")
    (license license:lgpl3)
  ))
odoo
